POST http://localhost:3001/api/v1/urls
Content-Type: application/json

{
    "fullUrl":"https://www.npmjs.com/package/nanoid"
}

###

POST http://localhost:3001/api/v1/urls
Content-Type: application/json

{
    "fullUrl":"invalid url"
}

###

POST http://localhost:3001/api/v1/urls
Content-Type: application/json

{
    "fullUrl":"too short"
}

###

GET http://localhost:3001/api/v1/urls/hDi0ym-
